language: python

sudo: false

cache:
  - pip

python:
 - "2.7"
 - "3.6"

addons:
 postgresql: "9.4"

env:
 - DJANGO_VERSION=1.8.18
 - DJANGO_VERSION=1.10.7
 - DJANGO_VERSION=1.11

install:
 - pip install -r requirements.txt
 - pip uninstall -y Django
 - pip install -q Django==$DJANGO_VERSION

script:
 - flake8 postgres_copy
 - coverage run setup.py test
 - coverage report -m

after_success:
 - coveralls
