language: python

sudo: false

cache:
  - pip

python:
 - "2.7"
 - "3.5"
 - "3.6"

env:
 - DJANGO_VERSION=1.8.17
 - DJANGO_VERSION=1.9.12
 - DJANGO_VERSION=1.10.6
 - DJANGO_VERSION=1.11

install:
 - pip install -r requirements.txt
 - pip uninstall -y Django
 - pip install -q Django==$DJANGO_VERSION

script:
 - flake8 postgres_copy
 - coverage run setup.py test

after_success:
 - coveralls
