language: python

python:
 - "2.7"
 - "3.3"
 - "3.4"

env:
 - DJANGO_VERSION=1.7
 - DJANGO_VERSION=1.8.2
 - DJANGO_VERSION=1.7
 - DJANGO_VERSION=1.8.2

install:
 - pip install -r requirements.txt
 - pip uninstall -y Django
 - pip install -q Django==$DJANGO_VERSION

script:
 - pep8 postgres_copy
 - pyflakes postgres_copy
 - coverage setup.py test

after_success:
 - coveralls
