language: python

sudo: required

cache:
  - pip

python:
 - "2.7"
 - "3.6"

addons:
 postgresql: "9.6"

env:
 - DJANGO_VERSION=1.11.*
 - DJANGO_VERSION=2.0.*

 matrix:
  exclude:
  - python: 3.6
    env: DJANGO_VERSION=1.11.*

install:
 - pip install flake8 coverage coveralls
 - pip install -q Django==$DJANGO_VERSION

script:
 - flake8 postgres_copy
 - coverage run setup.py test
 - coverage report -m

after_success:
 - coveralls
